[build]
  command = "echo 'No build step required'"
  publish = "frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
