[build]
  command = "echo 'No build step required'"
  publish = "frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test_function.py"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main_ui_server_netlify.py"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "backend"
