services:
  # Backend API Service
  - type: web
    name: provision-brokerage-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-70b-versatile
      - key: CALCOM_API_KEY
        sync: false
      - key: CALCOM_EVENT_TYPE_ID
        sync: false
      - key: CALCOM_USERNAME
        sync: false
      - key: CALCOM_API_URL
        value: https://api.cal.com/v1
      - key: DATABASE_URL
        fromDatabase:
          name: provision-brokerage-db
          property: connectionString
      - key: DEBUG
        value: false
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
      - key: SINCH_PROJECT_ID
        sync: false
      - key: SINCH_SERVICE_PLAN_ID
        sync: false
      - key: SINCH_ACCESS_KEY_ID
        sync: false
      - key: SINCH_KEY_SECRET
        sync: false
      - key: SINCH_PHONE_NUMBER
        sync: false

  # Frontend Static Site
  - type: web
    name: provision-brokerage-frontend
    runtime: static
    buildCommand: "echo 'No build needed for static frontend'"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database (PostgreSQL - recommended for production)
databases:
  - name: provision-brokerage-db
    plan: free
    databaseName: provision_brokerage
    user: provision_user

